### ISSUE TITLE
Don't include non-executable parts into coverage calculation

### ISSUE THREAD

**Issue by stephanpelikan** [camunda/camunda-bpm-process-test-coverage#22]
Hi,

I built a process including several lanes. Only one lane is executable and consists of only 9 nodes and 9 arrows. My tests result in every executeable node or line being colored green. Nevertheless I get only 32.7% coverage because the other lanes consists of 20 nodes and 17 arrows. 

(9 + 9) * 100 / (9 + 9 + 20 + 17) = 32.7272

This calculation proofes my consideration that the test coverage plugin does not exclude non-executable parts of the process diagram.

Stephan

**Comment by falko** [comment]
Do you mean you have non-executable Pools? Only a Pool or more precisely 
the Process represented by a Pool has the executable attribute. Lanes 
just partition a Pool but it is still one process.

Could you share your process model?

**Comment by RasPelikan** [comment]
Sorry for being imprecise, I have several pools each consisting lanes. However, the key message is to ignore non-executable elements.Stephan-------- Originalnachricht --------Betreff: Re: [camunda/camunda-bpm-process-test-coverage] Don't include non-executable parts into coverage calculation (#22)Von: Falko Menge An: camunda/camunda-bpm-process-test-coverage Cc: Subscribed Do you mean you have non-executable Pools? Only a Pool or more precisely 
the Process represented by a Pool has the executable attribute. Lanes 
just partition a Pool but it is still one process.

Could you share your process model?


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/camunda/camunda-bpm-process-test-coverage","title":"camunda/camunda-bpm-process-test-coverage","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/camunda/camunda-bpm-process-test-coverage"}},"updates":{"snippets":[{"icon":"PERSON","message":"@falko in #22: Do you mean you have non-executable Pools? Only a Pool or more precisely \nthe Process represented by a Pool has the executable attribute. Lanes \njust partition a Pool but it is still one process.\n\nCould you share your process model?\n"}],"action":{"name":"View Issue","url":"https://github.com/camunda/camunda-bpm-process-test-coverage/issues/22#issuecomment-315368775"}}}

**Comment by RasPelikan** [comment]
I added a fix for this. I would appreciate a review since I'm not sure that I found all correct places in the code.

Stephan
