### ISSUE TITLE
TestCoverageProcessEngineRule not reset for new test class when used in a super class

### ISSUE THREAD

**Issue by rweisleder** [camunda/camunda-bpm-process-test-coverage#43]
I want to use the TestCoverageProcessEngineRule in a super class, so that each test class has the same configuration.

```java
public abstract class ProcessDefinitionTest {

    private static final ProcessEngine processEngine = new ProcessCoverageInMemProcessEngineConfiguration().buildProcessEngine();

    @Rule
    @ClassRule
    public static final ProcessEngineRule processEngineRule = TestCoverageProcessEngineRuleBuilder.create(processEngine).assertClassCoverageAtLeast(0.1).build();

}

@Deployment(resources = "processes/Process_1.bpmn")
public class Process1Test extends ProcessDefinitionTest {

    @Test
    public void runProcess1() {
        processEngineRule.getRuntimeService().startProcessInstanceByKey("Process_1");
    }
}

@Deployment(resources = "processes/Process_2.bpmn")
public class Process2Test extends ProcessDefinitionTest {

    @Test
    public void runProcess2() {
        processEngineRule.getRuntimeService().startProcessInstanceByKey("Process_2");
    }
}
```

When I run a single test class, the tests are green. When I run multiple test classes in the same run, the second class (and every following class) fails with an exception.
```
java.lang.AssertionError: Class coverage can only be calculated if all tests deploy the same BPMN resources.
expected:<[ProcessDefinitionEntity[Process_2:1:103]]>
but was:<[ProcessDefinitionEntity[Process_1:2:6]]>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.camunda.bpm.extension.process_test_coverage.model.ClassCoverage.assertAllDeploymentsEqual(ClassCoverage.java:208)
        at org.camunda.bpm.extension.process_test_coverage.junit.rules.TestCoverageProcessEngineRule.handleClassCoverage(TestCoverageProcessEngineRule.java:342)
        at org.camunda.bpm.extension.process_test_coverage.junit.rules.TestCoverageProcessEngineRule.finished(TestCoverageProcessEngineRule.java:146)
```

I would except that the coverage is measured for every test class separately.

A complete demo is available at [rweisleder/camunda-process-coverage-demo](https://github.com/rweisleder/camunda-process-coverage-demo)

**Comment by zambrovski** [comment]
If you move you `static`class rule in a super class, it will get initialized once on the run of the first inheriting test. During this initialization, the process definition is stored. The limitation of the class rule is that it can report coverage from a list of process definitions passed during init. Since you are passing two different process definitions, the rule reports the invalid usage.

As a workaround, you can define the deployment annotation on the abstract class passing all process definitions, you want to test in inherited classes.

Your issue is fine, but this is not a bug, but just the way how the extension work. It doesn't support coverage metering on different process definitions sharing the same rule, but re-defining the deployments on subclass / individual methods...
