### ISSUE TITLE
The combination of the rule with other rules fails

### ISSUE THREAD

**Issue by zambrovski** [camunda/camunda-bpm-process-test-coverage#7]
I tried to use the test rule in combination with other rules (already initializing the process engine), which  results in an error. 

org.springframework.beans.factory.BeanDefinitionStoreException: IOException parsing XML document from class path resource [activiti.cfg.xml]; nested exception is java.io.FileNotFoundException: class path resource [activiti.cfg.xml] cannot be opened because it does not exist
Caused by: java.io.FileNotFoundException: class path resource [activiti.cfg.xml] cannot be opened because it does not exist

I'll analyse it in debugger and provide more details.

**Comment by zambrovski** [comment]
Hi folks,

I analyzed the code and found some potential flaws of your implementation. I'll try to summarize them here. 

Essentially, you are solving two problems with you extension: you collect coverage data and you render the coverage information to a report. I had a deeper look on the data collection. 

1. As far as I understand, you use a `@ClassRule` to initialize the `CoverageTestRunState` which holds a collection of elements covered by the test during the execution. This approach may work for small test scenarios, where all tests are contained in one test class, but fails if my process tests are distributed among several classes. 

2. In addition, the coupling between the listeners (collecting the data) and the `CoverageTestRunState` is very tight. This results in a problem if you use a custom Process Engine Configuration (which may be configured differently). For example, a direct cast of the History Event Handler to `FlowNodeHistoryEventHandler` might result in a problem.

3. As a result of this two assumptions above, you rely on the fact, that the engine is configured by yourself, which makes it almost impossible to combine your extension with any other tools (e.g. some of other extensions, or some configuration requiring a DB setup configured by some engine plugins...).

In my oppinion, there is no need to make all those assumptions, just to be able to collect coverage data. In particular, there is no need to assume that one class contains all tests for one process. Classic test coverage tools (cobertura, emma, clover) work without this assumptions. They instrument the code and collect information about the executed steps in the file system. In a post-test phase they analyze this information and generate reports out of it.

For process tests I propose to do the same. Register an engine plugin that collects the data and run a second step which analyzes this data and generates the report. I will provide you a simple implementation for this soon.

My idea is to allow both - creation of the reports out of JUnit rule itself (which will result in the same behaviour which is implemented now) and to provide an Apache Maven plugin for report generation, in order to be capable to generate reports which are focused on process models and not on test classes.

What do you think?

Kind regards,

Simon

**Comment by z0rbas** [comment]
Hello! Thank you for your feedback!

What other rule are you using? It would be interesting to reproduce this and adapt our code, either through functionality or better error reporting.
I recognize the exception and the usual cause, but a bit more context would help.

1. @ClassRule is used for collecting coverage data for the whole JUnit class. 
@Rule is used for collecting individual test method coverages. @Rule can be used on it's own. @ClassRule cannot since it requires data from the individual test runs.
Would JUnit Suite support solve your problem of distributed process test classes? Currently we haven't tested Suites but we could include them in further development.

2. It would be interesting to check if a customEventHandler can accumulate the history events since it would not be required to replace an already present historyEventHandler. 
Custom event handlers are stored in a list and can be extended without breaking existing configuration. You are right, the cast should at least be handled gracefully for the time being until a better solution is implemented.
   
The data collection and generation steps are already separated. The difference to the approach you suggested is that the data is stored in memory as objects. Using Suites would replace the filesystem based approach.

Opting-in/out of the graphical report generation could be a nice feature.

It would be great if you could provide sample projects or name the error cases in more detail in order to reproduce them. Any help is welcome!

Thanks,
Irmin

**Comment by martinschimak** [comment]
Hi @zambrovski - many thanks for your valuable insights. Can you please point me to the specific scenario of combinations of rules which does not work for you? I'd like to reproduce that and in particular like to find out whether we can fix the process engine initialisation/reusage issue soon/fast and eventually separate it from your more general refactoring proposals.

**Comment by lldata** [comment]
Maybe some of @zambrovski concerns about process engine configuration is adressed in #10 ?

**Comment by martinschimak** [comment]
Could well be that we are (almost) there with what we have since #10 - but would like to know more...
